<a href="https://colab.research.google.com/github/hebertgo/Prueba_Data_Science_Davivienda/blob/master/datos_no_estructurados_01_HebertGomez/Prueba_de_conocimientos_I_DNE_Davivienda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Nota: el siguiente notebook es una recuperación de una versión mejorada y analizada, no contiene la misma documentación y ordel que el original y las rutas son diferentes. Disculpas.**

In [ ]:
import os
import cv2
import numpy as np
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from skimage.feature import hog
import pandas as pd
# Definir rutas
input_folder = "/content/sample_data/images/"                                  #todas
output_folder_with_content = "/content/output_with_content/"
output_folder_without_content = "/content/output_without_content/"

# Crear carpetas de salida si no existen
os.makedirs(output_folder_with_content, exist_ok=True)
os.makedirs(output_folder_without_content, exist_ok=True)

# Preprocesamiento de imágenes y extracción de características
def preprocess_and_extract_features(img_path, img_size=(128, 128)):
    img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
    if img is None:
        return None
    img = cv2.resize(img, img_size)
    img = img / 255.0
    hog_features = hog(img, pixels_per_cell=(8, 8), cells_per_block=(2, 2), feature_vector=True)

    return hog_features

# Cargar y preprocesar las imágenes
image_paths = [os.path.join(input_folder, filename) for filename in os.listdir(input_folder) if filename.endswith(('.png'))]
features = [preprocess_and_extract_features(img_path) for img_path in image_paths]
features = [f for f in features if f is not None]
#Reducción de dimensionalidad para acelerar el clustering
pca = PCA(n_components=50)
reduced = pca.fit_transform(features)

# Aplicar K-means clustering
kmeans = KMeans(n_clusters=2, random_state=42)
kmeans.fit(features)
labels = kmeans.labels_
print(labels)



/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


[0 0 0 1 1 1 1 1 1 0 1 0 0 1 1 1 0 0 0 0 0 1 0 0 0 0 1 1 1 0 1 1 0 1 0 0 1
 0 0 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 1 1 0 0 1 1 0 1 0 0 1 0 1 1 0 1 1 1 1 1
 0 1 1 0 0 0 0 1 0 0 1 0 0 1 1 1 0 1 1 0 0 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 1
 0 0 0 0 0 0]


In [ ]:
for img_path, label in zip(image_paths, labels):
    if label == 1:
        destination = output_folder_with_content
    else:
        destination = output_folder_without_content
    os.rename(img_path, os.path.join(destination, os.path.basename(img_path)))

In [ ]:
import os
import cv2
import pandas as pd
from skimage.feature import hog

input_base_folder = "/content/sample_data/"
folders = ['blanco', 'documentos']                               # divida la data

# Dictionary to store image paths and their corresponding features
features_dict = {}

# Preprocessing of images and feature extraction
"""
def preprocess_and_extract_features(img_path, img_size=(128, 128)):
    img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
    if img is None:
        return None
    img = cv2.resize(img, img_size)
    img = img / 255.0
    hog_features = hog(img, pixels_per_cell=(8, 8), cells_per_block=(2, 2), feature_vector=True)
    return hog_features
"""
# Process each folder
for folder in folders:
    input_folder = os.path.join(input_base_folder, folder)
    image_paths = [os.path.join(input_folder, filename) for filename in os.listdir(input_folder) if filename.endswith('.png')]
    print(f"Image Paths in {folder}: {image_paths}")

    # Extract features for each image
    features = [preprocess_and_extract_features(img_path) for img_path in image_paths]
    features = [f for f in features if f is not None]
    print(f"Extracted Features in {folder}: {features}")

    # Store features in the dictionary with the folder name as the key
    features_dict[folder] = features

print("Features Dictionary:", features_dict)

# Convert features_dict to a DataFrame
data = []
for folder, features in features_dict.items():
    for feature in features:
        data.append([folder] + feature.tolist())

# Assuming HOG features length is known (e.g., 2916 for the given parameters)
feature_columns = [f'feature_{i}' for i in range(len(data[0]) - 1)]
df = pd.DataFrame(data, columns=['folder'] + feature_columns)

print(df)


Image Paths in blanco: ['/content/sample_data/blanco/page-262.png', '/content/sample_data/blanco/page-269.png', '/content/sample_data/blanco/page-268.png', '/content/sample_data/blanco/page-287.png', '/content/sample_data/blanco/page-202.png', '/content/sample_data/blanco/page-187.png', '/content/sample_data/blanco/page-257.png', '/content/sample_data/blanco/page-265.png', '/content/sample_data/blanco/page-196.png', '/content/sample_data/blanco/page-223.png', '/content/sample_data/blanco/page-276.png', '/content/sample_data/blanco/page-217.png', '/content/sample_data/blanco/page-230.png', '/content/sample_data/blanco/page-252.png', '/content/sample_data/blanco/page-170.png', '/content/sample_data/blanco/page-182.png', '/content/sample_data/blanco/page-188.png', '/content/sample_data/blanco/page-222.png', '/content/sample_data/blanco/page-204.png', '/content/sample_data/blanco/page-224.png', '/content/sample_data/blanco/page-208.png', '/content/sample_data/blanco/page-166.png', '/conten

In [ ]:
features_dict['documentos']

In [ ]:
# Imprimir el elemento en la posición 50 de la lista 'blanco' dentro del diccionario 'features_dict'
print(features_dict['blanco'][50])

# Crear un diccionario 'dict' con etiquetas y matrices
dict = {'label': [], 'matrix': []}

# Iterar sobre las carpetas en 'folders'
for j in folders:
    # Imprimir la longitud de la lista en features_dict[j]
    print(len(features_dict[j]))

    # Iterar sobre los elementos en features_dict[j]
    for i in range(len(features_dict[j])):
        # Agregar la etiqueta 'j' al diccionario 'dict'
        dict['label'].append(j)

        # Agregar la matriz en features_dict[j][i] al diccionario 'dict'
        dict['matrix'].append(features_dict[j][i])

# Crear un DataFrame 'df2' a partir del diccionario 'dict'
df2 = pd.DataFrame(dict)
print(df2)

# Dividir los datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(df2['matrix'], df2['label'], test_size=0.1, random_state=42)

# Convertir los datos de entrenamiento a un formato adecuado para el modelo
X_train = np.array([np.array(x) for x in X_train])

# Codificar las etiquetas 'y_train' numéricamente
le = LabelEncoder()
y_train_numerical = le.fit_transform(y_train)
y_train = y_train_numerical.astype(np.float32)

# Definir y compilar el modelo de red neuronal
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(8100,)),  # Cambiar la forma de entrada aquí según sea necesario
    keras.layers.Dense(128, activation=tf.nn.relu),
    keras.layers.Dense(2, activation=tf.nn.softmax)
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Entrenar el modelo
model.fit(X_train, y_train, epochs=10)

# Evaluar el modelo con datos de prueba
X_test = np.array([np.array(x) for x in X_test])
y_test_numerical = le.fit_transform(y_test)
y_test = y_test_numerical.astype(np.float32)
accuracy = model.evaluate(X_test, y_test)[1]
print(f"Exactitud: {accuracy}")


[0. 0. 0. ... 0. 0. 0.]
blanco
125
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
documentos
100
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
          label                                             matrix
0        blanco  [0.16624394044379803, 0.010145057728887791, 0....
1        blanco  [0.20846597598157224, 0.19187574169586025, 0.1...
2        blanco  [0.1912105340877278, 0.0, 0.011506916064027902...
3 

In [ ]:
from sklearn.metrics import confusion_matrix
predictions = model.predict(X_test)
print(X_test)
predicted_labels = np.argmax(predictions, axis=1)
predicted_labels_in = le.inverse_transform(predicted_labels)
print(predicted_labels_in)
# Decodificar las etiquetas predichas

# Generate confusion matrix
cm = confusion_matrix(y_test, predicted_labels)

# Print confusion matrix
print(cm)


1/1 [==============================] - 0s 56ms/step
[[0.25339807 0.         0.06015972 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.29848845 0.         0.03547091 ... 0.         0.         0.        ]
 ...
 [0.34592586 0.         0.         ... 0.         0.         0.        ]
 [0.57039016 0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]
['blanco' 'documentos' 'blanco' 'documentos' 'documentos' 'documentos'
 'documentos' 'blanco' 'documentos' 'documentos' 'blanco' 'blanco'
 'documentos' 'blanco' 'blanco' 'blanco' 'blanco' 'documentos' 'blanco'
 'documentos' 'blanco' 'blanco' 'documentos']
[[12  0]
 [ 0 11]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split

# Definición del modelo CNN

# Preparación de los datos
X = df.drop('folder', axis=1).values  # Seleccionar todas las características excepto 'folder'
le = LabelEncoder()
df['folder'] = le.fit_transform(df['folder'])  # Codificar la columna 'folder' numéricamente
y = df['folder'].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)
X_train = X_train.astype('float32')

# Definición del modelo de red neuronal secuencial
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(8100,)),  # Cambiar la forma de entrada aquí según sea necesario
    keras.layers.Dense(128, activation=tf.nn.relu),
    keras.layers.Dense(2, activation=tf.nn.softmax)
])

# Compilación del modelo
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Entrenamiento del modelo
model.fit(X_train, y_train, epochs=10)

# Evaluación del modelo
accuracy = model.evaluate(X_test, y_test)[1]
print(f"Exactitud: {accuracy}")



Epoch 1/10
7/7 [==============================] - 2s 25ms/step - loss: 0.2121 - accuracy: 0.8861
Epoch 2/10
7/7 [==============================] - 0s 20ms/step - loss: 0.0478 - accuracy: 0.9901
Epoch 3/10
7/7 [==============================] - 0s 22ms/step - loss: 0.0346 - accuracy: 1.0000
Epoch 4/10
7/7 [==============================] - 0s 42ms/step - loss: 0.0255 - accuracy: 1.0000
Epoch 5/10
7/7 [==============================] - 0s 34ms/step - loss: 0.0219 - accuracy: 1.0000
Epoch 6/10
7/7 [==============================] - 0s 24ms/step - loss: 0.0191 - accuracy: 1.0000
Epoch 7/10
7/7 [==============================] - 0s 24ms/step - loss: 0.0173 - accuracy: 1.0000
Epoch 8/10
7/7 [==============================] - 0s 22ms/step - loss: 0.0157 - accuracy: 1.0000
Epoch 9/10
7/7 [==============================] - 0s 36ms/step - loss: 0.0142 - accuracy: 1.0000
Epoch 10/10
1/1 [==============================] - 0s 238ms/step - loss: 0.0110 - accuracy: 1.0000
Accuracy: 1.0


In [ ]:

predictions = model.predict(X_test)
predicted_labels = np.argmax(predictions, axis=1)

# Decodificar las etiquetas predichas
predicted_labels = le.inverse_transform(predicted_labels)
print(predicted_labels)

1/1 [==============================] - 0s 66ms/step
['blanco' 'documentos' 'blanco' 'documentos' 'documentos' 'documentos'
 'documentos' 'blanco' 'documentos' 'documentos' 'blanco' 'blanco'
 'documentos' 'blanco' 'blanco' 'blanco' 'blanco' 'documentos' 'blanco'
 'documentos' 'blanco' 'blanco' 'documentos']


In [ ]:
from sklearn.metrics import confusion_matrix

predicted_labels = le.transform(predicted_labels)
# Generate confusion matrix
cm = confusion_matrix(y_test, predicted_labels)

# Print confusion matrix
print(cm)


[[12  0]
 [ 0 11]]


In [ ]:
# Define the path to the file you want to delete
for i in os.listdir("/content/output_without_content/"):

  file_path =os.path.join( "/content/output_without_content/",i)
  os.remove(file_path)



In [ ]:
l={}
a=[]
a.append(1)
a.append(1)
l['a']=a
print(l)

{'a': [1, 1]}
